server:
  port: 8090
spring:
  application:
    name: file-processor
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fileprocessor_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  batch:
    initialize-schema: always
fileprocessor:
  upload-dir: ./uploads
  chunk-size: 1000
  pool-size: 4
gateway:
  url: http://localhost:8080
